version: '3.8'

services:
  # 1. RabbitMQ (Dịch vụ gửi tin nhắn)
  rabbitmq:
    image: rabbitmq:3.9-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # Cổng cho các ứng dụng Spring Boot
      - "15672:15672" # Cổng cho giao diện quản lý web
    networks:
      - ibanking-net

  # 2. Redis (Dịch vụ Cache để lưu OTP)
  redis:
    image: redis:6.2-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - ibanking-net

  # 3. Database cho User Service
  user-db:
    image: postgres:14-alpine
    container_name: user-db
    ports:
      - "5432:5432" # Mở cổng 5432 của máy thật
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=user_db
    networks:
      - ibanking-net

  # 4. Database cho Student Service
  student-db:
    image: postgres:14-alpine
    container_name: student-db
    ports:
      - "5433:5432" # Mở cổng 5433 của máy thật (để tránh trùng 5432)
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=student_db
    networks:
      - ibanking-net

  # 5. Service Registry (Eureka)
  service-registry:
    build:
      context: ./service-registry # Bảo Docker build từ thư mục ./service-registry
    container_name: service-registry
    ports:
      - "8761:8761" # Mở cổng Eureka
    networks:
      - ibanking-net

# Định nghĩa mạng chung cho các container
networks:
  ibanking-net:
    driver: bridge